# Generated by Django 5.0.4 on 2024-06-01 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_alter_repository_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='type',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('paid', 'Paid')], default='public', max_length=10),
        ),
    ]
