# Generated by Django 5.0.4 on 2024-05-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='token',
            field=models.CharField(default='373a4807-31b0-40b9-9f70-4091c5dff8e1', max_length=36),
            preserve_default=False,
        ),
    ]
