# Generated by Django 5.0.4 on 2024-05-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_profile_yandex_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='yandex_token',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
